# ======================================================================
#    srm_recovery_engine_v1.py — SRM AUTO-RECOVERY ENGINE v1
# ======================================================================
#  Funciones del sistema:
#   - Detectar fallas estructurales
#   - Reparar carpetas críticas
#   - Regenerar archivos esenciales
#   - Reparar JSON corruptos
#   - Regenerar logs base
#   - Documentar todas las acciones de recuperación
#
#  Resultado:
#   - recovery_report.json
#   - recovery_summary.md
#
# ======================================================================

import os
import json
from datetime import datetime

BASE = r"C:\SRM_ADSI\05_pipeline"
HEALTH_DIR = os.path.join(BASE, "health")
UPDATES_DIR = os.path.join(BASE, "updates")

REC_DIR = os.path.join(BASE, "recovery")
os.makedirs(REC_DIR, exist_ok=True)

OUT_JSON = os.path.join(REC_DIR, "recovery_report.json")
OUT_MD = os.path.join(REC_DIR, "recovery_summary.md")


CRITICAL_FOLDERS = [
    r"C:\SRM_ADSI\00_docs",
    r"C:\SRM_ADSI\02_cleaned_normalized",
    r"C:\SRM_ADSI\03_knowledge_base",
    r"C:\SRM_ADSI\05_pipeline",
    r"C:\SRM_ADSI\06_shopify",
    r"C:\SRM_ADSI\08_branding",
]

CRITICAL_FILES = [
    "srm_runtime_controller_v1.py",
    "srm_diagnostics_v1.py",
    "srm_update_manager_v1.py",
    "srm_health_monitor_v1.py",
    "srm_anomaly_detector_v1.py",
    "srm_system_report_v1.py",
    "srm_maintenance_engine_v1.py",
]

ESSENTIAL_JSON = {
    "runtime_state": os.path.join(BASE, "runtime_state.json"),
    "runtime_log": os.path.join(BASE, "runtime_log.json"),
    "health_status": os.path.join(HEALTH_DIR, "health_status.json"),
    "events_log": os.path.join(HEALTH_DIR, "events_log.json"),
    "version_manifest": os.path.join(UPDATES_DIR, "version_manifest.json"),
    "system_report": os.path.join(HEALTH_DIR, "system_report.json"),
}


# ----------------------------------------------------------------------
# Utilidades
# ----------------------------------------------------------------------
def load_json(path):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except:
        return None


def save_json(data, path):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=4, ensure_ascii=False)


def recreate_json_placeholder(path):
    placeholder = {
        "status": "REGENERATED",
        "generated_at": datetime.now().isoformat(),
        "note": "Archivo reconstruido automáticamente por SRM Recovery Engine."
    }
    save_json(placeholder, path)
    return placeholder


def recreate_script_placeholder(path):
    template = f"""
# Auto-regenerated placeholder for {os.path.basename(path)}
# Generated by SRM Recovery Engine at {datetime.now().isoformat()}
# This file must be replaced with a proper implementation.

print("This is a regenerated placeholder for {os.path.basename(path)}.")
"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(template)

    return template


# ----------------------------------------------------------------------
# RECOVERY
# ----------------------------------------------------------------------
def run_recovery():

    print("\n=====================================================")
    print("          SRM — AUTO RECOVERY ENGINE v1")
    print("=====================================================\n")

    report = {
        "timestamp": datetime.now().isoformat(),
        "folders_recreated": [],
        "files_recreated": [],
        "json_repaired": [],
        "json_recreated": [],
        "notes": []
    }

    # --------------------------------------------------
    # 1. REPARAR CARPETAS CRÍTICAS
    # --------------------------------------------------
    for folder in CRITICAL_FOLDERS:
        if not os.path.exists(folder):
            os.makedirs(folder, exist_ok=True)
            report["folders_recreated"].append(folder)
            print(f"✔ Carpeta recreada: {folder}")

    # --------------------------------------------------
    # 2. REGENERAR ARCHIVOS CRÍTICOS
    # --------------------------------------------------
    for filename in CRITICAL_FILES:
        path = os.path.join(BASE, filename)
        if not os.path.exists(path):
            recreate_script_placeholder(path)
            report["files_recreated"].append(path)
            print(f"✔ Archivo crítico regenerado (placeholder): {path}")

    # --------------------------------------------------
    # 3. REPARAR JSON ESENCIALES
    # --------------------------------------------------
    for key, path in ESSENTIAL_JSON.items():
        if not os.path.exists(path):
            recreate_json_placeholder(path)
            report["json_recreated"].append(path)
            print(f"✔ JSON esencial recreado: {path}")
        else:
            data = load_json(path)
            if data is None:  # JSON corrupto
                recreate_json_placeholder(path)
                report["json_repaired"].append(path)
                print(f"✔ JSON corrupto reparado: {path}")

    # --------------------------------------------------
    # 4. GUARDAR REPORTE
    # --------------------------------------------------
    save_json(report, OUT_JSON)

    md = f"""
# 🛠 SRM — Recovery Report v1

Generado: **{report['timestamp']}**

---

## 📁 Carpetas recreadas
